//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADASO_AgreementApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementMaill
    {
        public int Id { get; set; }
        public Nullable<int> AgreementID { get; set; }
        public Nullable<int> MaillID { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual Agreementt Agreementt { get; set; }
        public virtual Maill Maill { get; set; }
        public virtual Adminn Adminn { get; set; }
    }
}
