//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADASO_AgreementApp.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADASOEntities4 : DbContext
    {
        public ADASOEntities4()
            : base("name=ADASOEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminn> Adminns { get; set; }
        public virtual DbSet<AgreementMaill> AgreementMaills { get; set; }
        public virtual DbSet<Agreementt> Agreementts { get; set; }
        public virtual DbSet<Maill> Maills { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
