//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADASO_AgreementApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLAdmin()
        {
            this.TBLAgreement1 = new HashSet<TBLAgreement>();
        }
    
        public int AdminID { get; set; }
        public string AdminName { get; set; }
        public string AdminSurname { get; set; }
        public string Tel { get; set; }
        public string AdminMail { get; set; }
        public string TC { get; set; }
        public string Image { get; set; }
        public int AgreementNo { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }
    
        public virtual TBLAgreement TBLAgreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAgreement> TBLAgreement1 { get; set; }
    }
}
