//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADASO_AgreementApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLAgreement()
        {
            this.TBLAdmin = new HashSet<TBLAdmin>();
        }
    
        public int AgreementNo { get; set; }
        public string AgrTitle { get; set; }
        public string AgrContent { get; set; }
        public string AgrFinishDate { get; set; }
        public string AgrStartDate { get; set; }
        public string Image { get; set; }
        public string CompanyName { get; set; }
        public int AdminID { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLAdmin> TBLAdmin { get; set; }
        public virtual TBLAdmin TBLAdmin1 { get; set; }
    }
}
