//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADASO_AgreementApp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreementt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreementt()
        {
            this.AgreementMaills = new HashSet<AgreementMaill>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string Content { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public string File { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string ReminderSentFor { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual Adminn Adminn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgreementMaill> AgreementMaills { get; set; }
    }
}
